spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 3000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      eager: true
      web-context-unify: false
      transport:
        dashboard: localhost:8080
feign:
  sentinel:
    enabled: true
