server:
  port: 11000
spring:
  application:
    name: seata-business
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/order_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false